version: 2

sources:
  - name: raw  # Schema name in your warehouse
    database: postgres  # Optional depending on your target
    schema: public
    tables:
      - name: daily_jokes
        description: "Daily jokes ingested from the external jokes API"
        freshness:
          warn_after: {count: 7, period: day}
          error_after: {count: 14, period: day}
        loaded_at_field: created_at  # Optional: if you track load timestamp

      - name: transactions
        description: "All user transactions processed through the system"

      - name: users
        description: "Registered users with their profiles and preferences"

      - name: employees
        description: "Internal employee data synced from the HR system"
