version: 2

sources:
  - name: crm_raw  # Schema name in your warehouse
    database: postgres  # Optional depending on your target
    schema: public
    tables:
      
      - name: transactions
        description: "All user transactions processed through the system"

      - name: users
        description: "Registered users with their profiles and preferences"

      - name: employees
        description: "Internal employee data synced from the HR system"
